# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField()),
                ('digital_code', models.PositiveSmallIntegerField(unique=True)),
                ('char_code', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField()),
                ('contacts', models.CharField(blank=True, max_length=120)),
                ('comment', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField()),
                ('digital_code', models.PositiveSmallIntegerField(unique=True)),
                ('char_code', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField()),
                ('digital_code', models.PositiveSmallIntegerField(unique=True)),
                ('char_code', models.CharField(max_length=3, unique=True)),
                ('upload_rates', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_type', models.CharField(choices=[('EXPENCE', 'EXPENCE'), ('INCOME', 'INCOME')], default='EXPENCE', max_length=30)),
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('document_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=16)),
                ('comment', models.CharField(blank=True, max_length=120)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expence_counterparty', to='mymoneymanager.Counterparties')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expence_currency', to='mymoneymanager.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expence_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=16)),
                ('comment', models.CharField(blank=True, max_length=120)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Document_expense', to='mymoneymanager.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_rate', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=16)),
                ('multiplicity', models.PositiveIntegerField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exchange_rates', to='mymoneymanager.Bank')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exchange_rates_base_currency', to='mymoneymanager.Currency')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exchange_rates_currency', to='mymoneymanager.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Expense_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField()),
                ('quantitative', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Income_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallets_and_Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField()),
                ('wallet_type', models.CharField(choices=[('Cash', 'Cash'), ('Credit_Card', 'Credit card')], default='Cash', max_length=30)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallets_and_Accounts_currency', to='mymoneymanager.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='documentitem',
            name='expense_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expense_item_expense_item', to='mymoneymanager.Expense_item'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='income_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Income_item_income_item', to='mymoneymanager.Income_item'),
        ),
        migrations.AddField(
            model_name='document',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expence_wallet', to='mymoneymanager.Wallets_and_Accounts'),
        ),
        migrations.AddField(
            model_name='bank',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='mymoneymanager.Country'),
        ),
    ]
